package.json
src/lib/components/page/diffchart/DiffchartSongMobile.svelte

+ Fixed DiffchartSongMobile text overflow

fix DiffchartSongMobile

---

package.json
src/lib/components/page/song/[songNo]/SongDataDisplay.svelte

+ /song/[songNo] 아티스트 표시 오류 수정

version: 0.3.1

---

package.json
src/lib/components/page/song/[songNo]/AlertDisplay.svelte
src/lib/module/common/song/song.server.ts
src/routes/(main)/+layout.ts

+ 무조건 mysql에서 song 데이터를 요청하도록 변경 (db 변경 시 추후 수정)

ver: 0.3.2

---

src/lib/module/common/i18n/lang/en.ts

English Translation

---

src/lib/components/page/song/SearchBox-GenreItem.svelte
src/routes/(main)/song/+page.svelte

```diff
+ 장르 검색 박스 크기 이슈 수정(#33)
```

장르 검색 박스 크기 이슈 수정

---

src/lib/components/page/diffchart/DiffchartSection.svelte
src/lib/components/page/diffchart/DiffchartSectionName.svelte

서열표 카운팅 이슈 수정

---

src/lib/components/page/dani/DaniCondition.svelte
src/lib/components/page/song/[songNo]/CourseDisplay-mobile.svelte
src/lib/components/page/song/[songNo]/CourseDisplay-pc.svelte

```diff
+ 곡 상세페이지 단위 표기부분 오류 수정
```

곡 상세페이지 단위 표기부분 오류

---

src/lib/components/page/song/[songNo]/CourseContainer.svelte
src/lib/components/page/song/[songNo]/CourseDisplay-mobile.svelte
src/lib/components/page/song/[songNo]/CourseDisplay-pc.svelte
src/lib/components/page/song/[songNo]/CourseDisplay.svelte

연타 시간 자릿수 오류 수정

---

src/routes/(main)/+page.svelte

closes #74
#75 의 내용과 같습니다.
위 이슈에 대응한 PR입니다.
현재 메인 페이지가 없으므로 song으로 redirect를 시키는 방향으로 수정하는 것이 좋아보입니다.
추후 메인 페이지가 생겼을 시 그 때 리다이렉트를 빼는 방향으로 적용하는 것이 좋아보입니다.

fix: 메인화면 곡화면으로 리다이렉트

---

src/lib/components/page/song/[songNo]/SongDataDisplay.svelte
src/lib/components/page/song/[songNo]/SongDataDisplayTag.svelte

SongDataDisplay에서 일부 항목은 tag 형식으로 나타냄

---

src/lib/module/server/hooks/ban-controller.server.ts

banController에서 clientAddress를 알 수 없는 경우 종료되던 문제 수정

---

package-lock.json
package.json
src/lib/module/server/hooks/allow-origin.ts

feat: allowOrigin에 credentials 옵션 추가

---

src/lib/components/page/song/[songNo]/CourseDisplay-pc.svelte
src/lib/module/common/i18n/i18n.ts

테이블 레이아웃 깨짐 수정

---

src/lib/components/page/gamecenter/FavoriteButton.svelte
src/lib/components/page/gamecenter/GamecenterInfo.svelte
src/lib/components/page/gamecenter/KakaoMap.svelte
src/lib/module/page/gamecenter/gamecenter.server.ts
src/lib/module/page/gamecenter/types.ts

version: 0.5.1

---

src/lib/components/page/measures/MeasureSong.svelte
src/lib/components/page/measures/MeasureTable.svelte

fix: measure layout

---

src/lib/components/common/PageTitle.svelte
src/lib/module/common/i18n/i18n.ts
src/lib/module/common/i18n/lang/en.ts
src/lib/module/common/i18n/lang/ja.ts
src/lib/module/common/i18n/lang/ko.ts
src/routes/(main)/auth/login/+page.svelte
src/routes/(main)/auth/user/+page.svelte
src/routes/(main)/auth/user/donder/+page.svelte
src/routes/(main)/dani/[version]/+page.svelte
src/routes/(main)/diffchart/(dedicated diffchart)/clear/[level]/+page.svelte
src/routes/(main)/gamecenter/+page.svelte
src/routes/(main)/gamecenter/report/+page.svelte
src/routes/(main)/measures/+page.svelte
src/routes/(main)/song/+page.svelte
src/routes/(main)/song/[songNo=songNo]/+page.svelte
src/routes/(main)/song/[songNo=songNo]/edit/+page.svelte
src/routes/(main)/song/add/+page.svelte

feat: 페이지별 제목 추가

---

package.json
src/lib/components/page/gamecenter/GamecenterInfo.svelte
src/lib/module/common/i18n/lang/en.ts

Version: 0.7.2

---

package.json
src/lib/components/layout/main/Aside-NewSong.svelte
src/lib/module/layout/theme.ts
src/routes/(main)/+layout.server.ts
src/routes/(main)/+layout.svelte
static/assets/css/main.css

It can reduce the first loading(rendering) time.

feat: add theme to cookie so that server can know which theme browser is using

---

src/lib/module/common/cookieStore.client.ts
src/lib/module/layout/theme.ts

fix: cookie store polyfill

---

src/lib/components/page/diffchart/Diffchart.svelte
src/routes/(main)/diffchart/(dedicated diffchart)/clear/[level]/+page.server.ts
src/routes/(main)/diffchart/(dedicated diffchart)/clear/[level]/+page.svelte

from [issue #142](https://github.com/taikowiki/taikowiki-svelte/issues/142)

feat: added loading donder data when enter diffchart page

---

src/lib/components/page/diffchart/Diffchart.svelte
src/lib/components/page/diffchart/DiffchartSection.svelte
src/lib/components/page/diffchart/DiffchartSectionName.svelte
src/lib/components/page/diffchart/DiffchartSongPc.svelte
src/lib/module/common/song/song.server.ts
src/routes/(main)/diffchart/(dedicated diffchart)/clear/[level]/+page.server.ts
src/routes/(main)/diffchart/+layout.server.ts

서열표 페이지와 songDBController 부분들을 좀 더 읽기 쉽도록 변경하였습니다.

refactor: DiffchartPage & songDBController

---

package.json
src/lib/components/page/diffchart/Diffchart.svelte
src/lib/components/page/diffchart/DiffchartSection.svelte
src/lib/components/page/diffchart/DiffchartSectionName.svelte
src/lib/components/page/diffchart/DiffchartSongPc.svelte
src/lib/module/common/song/song.server.ts
src/lib/module/common/user/user.server.ts
src/routes/(main)/diffchart/(dedicated diffchart)/clear/[level]/+page.server.ts
src/routes/(main)/diffchart/+layout.server.ts

Version: 0.8.4

---

src/lib/components/page/diffchart/DiffchartSection.svelte
src/lib/components/page/diffchart/DiffchartSectionName.svelte

개인적으로 접은 상태 localStorage에다 저장해서 
페이지 다시 불러와도 상태 유지하고 싶은데 어떻게 생각하시나요

feat: 서열표 접기 기능

---

package.json
src/lib/components/page/auth/user/donder/DonderData.svelte
src/lib/components/page/diffchart/DiffchartSection.svelte
src/lib/components/page/diffchart/DiffchartSectionName.svelte
src/lib/module/common/i18n/lang/ja.ts
src/lib/module/common/i18n/md/ja/ratingExplanation.md
src/lib/module/common/i18n/md/ja/ratingUploadGuide.md
src/lib/module/common/i18n/md/ko/ratingUploadGuide.md
src/lib/module/common/user/types.ts
src/lib/module/common/user/user.client.ts
src/lib/module/common/user/user.server.ts
src/routes/(main)/auth/user/donder/+page.svelte
src/routes/(main)/auth/user/donder/+page.ts
src/routes/api/user/ranking/+server.ts
src/routes/api/user/update-rating/+server.ts

```diff
+ 더 많은 페이지에 i18n 추가
+ 서열표 접기 기능
+ 곡 플레이 데이터를 덮어씌우지 않고 병합하도록 변경
```

version: 0.10.3

---

src/lib/components/page/rating/me/SongRatingItem.svelte
src/lib/components/page/rating/me/SongRatings.svelte
src/lib/components/page/rating/user/OtherSongRatings.svelte
src/lib/module/common/i18n/lang/en.ts
src/lib/module/common/i18n/lang/ja.ts
src/lib/module/common/i18n/lang/ko.ts
vite.config.ts

#322 
---
서열표 페이지 내에 있는 이미지 다운로드 버튼을 참조하여 추가 해놓았고요. 
외부 이미지 같은 경우 프록시를 활용하여 이미지 저장시에도 무사히 불러올 수 있게 수정하였습니다.
공유 기능은 추후 API 확인해본 후 추가하겠습니다,,,

feat: add download image rating table

---

src/lib/components/layout/main/ServerTheme.svelte
src/routes/(main)/+layout.svelte

<svelte:head>에 style 쓰면 vercel에서 오류남

hotfix: serverTheme

---

src/lib/module/common/wikidoc/server/dbController.server.ts
src/routes/(main)/doc/+page.svelte
src/routes/(main)/doc/search/+page.server.ts
src/routes/(main)/doc/search/+page.svelte

feat: search에서 query가 비어있을 경우 모든 문서 보여줌

---

package.json
src/lib/components/page/measures/MeasureGroup.svelte
src/lib/components/page/measures/MeasureSubGroup.svelte
src/lib/components/page/measures/MeasureTable.svelte
src/lib/module/common/user/user.server.ts
src/routes/(main)/rating/user/[UUID]/+page.server.ts

version: 1.0.2
